language: node_js
node_js:
  - "5"
  - "4"
  - "0.12"
  - "iojs"
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
script: npm run coverage
after_success: 'npm run coveralls'
